### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by F1owey** [MC-XiaoHei/ISeeYou#16]
开启了对themis的支持 服务端无限报错
[13:28:34 ERROR]: Could not pass event PlayerMoveEvent to ISeeYou v1.1.3
java.lang.NullPointerException: null
        at cn.xor7.iseeyou.EventListener.onPlayerMove(EventListener.kt:82) ~[ISeeYou-1.1.3-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor370.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:53) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1572) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"da47a6f"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by MC-XiaoHei** [comment]
`/reload`导致的。。
我看看能不能修吧。这个问题我也遇到了。目前的解决方案是reload后让所有玩家重新进入游戏。

**Comment by MC-XiaoHei** [comment]
应当在下个版本修复

**Comment by MC-XiaoHei** [comment]
应在v1.1.4修复。

**Comment by F1owey** [comment]
配置文件不变？
