### ISSUE TITLE
自动清理过期录像时服务器无响应

### ISSUE THREAD

**Issue by iaddda** [MC-XiaoHei/ISeeYou#20]
即使没有过期录像仍然会触发，之后服务器自动关机
[2024-03-27-1.log](https://github.com/MC-XiaoHei/ISeeYou/files/14772872/2024-03-27-1.log)

以下是config.toml的内容

deleteTmpFileOnLoad = true
pauseInsteadOfStopRecordingOnPlayerQuit = false
recordPath = "replay/player/${name}@${uuid}"

[pauseRecordingOnHighSpeed]
enabled = false
threshold = 20.0

[filter]
checkBy = "name"
recordMode = "blacklist"
blacklist = []

[clearOutdatedRecordFile]
enabled = true
days = 5

[recordSuspiciousPlayer]
enableThemisIntegration = false
enableMatrixIntegration = false
recordMinutes = 10
recordPath = "replay/suspicious/Themis/${name}@${uuid}"

**Comment by MC-XiaoHei** [comment]
@CerealAxis 来看看。

**Comment by MC-XiaoHei** [comment]
无法复现，能否给出服务器文件夹的截图？
但是确实找到了一些问题，你可以尝试使用最新的[dev build](https://github.com/MC-XiaoHei/ISeeYou/actions/runs/8566663744/artifacts/1387580226)进行测试

**Comment by iaddda** [comment]
抱歉现在才回复。
换用dev build重启服务器时，插件开始清理过期录像，后台记录如下：

[15:56:06 信息]: [ISeeYou] Enabling ISeeYou v1.1.4
[15:56:06 信息]: [ISeeYou] Start to delete outdated recordings in replay/player and replay/suspicious/Themis
[15:56:07 信息]: [ISeeYou] Deleted recording file: 2024-03-26@19-42-34.mcpr
[15:56:07 信息]: [ISeeYou] Deleted recording file: 2024-03-27@22-53-58.mcpr
[15:56:07 信息]: [ISeeYou] Deleted recording file: 2024-03-28@20-37-47.mcpr
……
[15:56:08 信息]: [ISeeYou] Deleted recording file: 2024-03-31@20-41-50.mcpr
[15:56:08 信息]: [ISeeYou] Deleted recording file: 2024-04-01@14-53-40.mcpr
[15:56:08 ERROR]: [ISeeYou] Error occurred while cleaning outdated recordings: replay/suspicious/Themis
[15:56:08 警告]: java.nio.file.NoSuchFileException: replay/suspicious/Themis
[15:56:08 警告]:        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[15:56:08 警告]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[15:56:08 警告]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[15:56:08 警告]:        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[15:56:08 警告]:        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
[15:56:08 警告]:        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[15:56:08 警告]:        at java.base/java.nio.file.Files.readAttributes(Files.java:1849)
[15:56:08 警告]:        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
[15:56:08 警告]:        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
[15:56:08 警告]:        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
[15:56:08 警告]:        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
[15:56:08 警告]:        at java.base/java.nio.file.Files.walk(Files.java:3917)
[15:56:08 警告]:        at java.base/java.nio.file.Files.walk(Files.java:3972)
[15:56:08 警告]:        at ISeeYou-1.1.4-dev.jar//cn.xor7.iseeyou.ISeeYou.cleanOutdatedRecordings(ISeeYou.kt:230)
[15:56:08 警告]:        at ISeeYou-1.1.4-dev.jar//cn.xor7.iseeyou.ISeeYou.onEnable(ISeeYou.kt:68)
[15:56:08 警告]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[15:56:08 警告]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[15:56:08 警告]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[15:56:08 警告]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[15:56:08 警告]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:644)
[15:56:08 警告]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:555)
[15:56:08 警告]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669)
[15:56:08 警告]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426)
[15:56:08 警告]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[15:56:08 警告]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1130)
[15:56:08 警告]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314)
[15:56:08 警告]:        at java.base/java.lang.Thread.run(Thread.java:1589)

[15:56:21 信息]: [ISeeYou] Start to delete outdated recordings in replay/player and replay/suspicious/Themis
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 信息]: [ISeeYou] No outdated recording files found to delete.
[15:56:21 ERROR]: [ISeeYou] Error occurred while cleaning outdated recordings: replay/suspicious/Themis
[15:56:21 警告]: java.nio.file.NoSuchFileException: replay/suspicious/Themis
[15:56:21 警告]:        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[15:56:21 警告]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[15:56:21 警告]:        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[15:56:21 警告]:        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[15:56:21 警告]:        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
[15:56:21 警告]:        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[15:56:21 警告]:        at java.base/java.nio.file.Files.readAttributes(Files.java:1849)
[15:56:21 警告]:        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
[15:56:21 警告]:        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
[15:56:21 警告]:        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
[15:56:21 警告]:        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
[15:56:21 警告]:        at java.base/java.nio.file.Files.walk(Files.java:3917)
[15:56:21 警告]:        at java.base/java.nio.file.Files.walk(Files.java:3972)
[15:56:21 警告]:        at ISeeYou-1.1.4-dev.jar//cn.xor7.iseeyou.ISeeYou.cleanOutdatedRecordings(ISeeYou.kt:230)
[15:56:21 警告]:        at ISeeYou-1.1.4-dev.jar//cn.xor7.iseeyou.ISeeYou.access$cleanOutdatedRecordings(ISeeYou.kt:38)
[15:56:21 警告]:        at ISeeYou-1.1.4-dev.jar//cn.xor7.iseeyou.ISeeYou$onEnable$2.run(ISeeYou.kt:75)
[15:56:21 警告]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:93)
[15:56:21 警告]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:481)
[15:56:21 警告]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1141)
[15:56:21 警告]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314)
[15:56:21 警告]:        at java.base/java.lang.Thread.run(Thread.java:1589)

之后服务器正常启动，检查replay文件夹发现过期录像被正常清理了。
config.toml的内容与之前发的相同（没有开启Themis反作弊支持）。
总体上正常了，感谢。

**Comment by CerealAxis** [comment]
🎉🎉🎉

**Comment by MC-XiaoHei** [comment]
@CerealAxis 你看看给那边加个文件夹是否存在的判断吧，应该就不会报错了

**Comment by CerealAxis** [comment]
我过几天闲了再改改。最近几天得赶作业😩
