### ISSUE TITLE
WorldGuard 疑似跟 ISeeYou 冲突

### ISSUE THREAD

**Issue by YuanYuanOwO** [MC-XiaoHei/ISeeYou#23]
```
[15:19:55 ERROR]: Could not pass event PlayerTeleportEvent to WorldGuard v7.0.9+5934e49
com.google.common.util.concurrent.UncheckedExecutionException: me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for '0e8ef417-fae9-4106-9cab-d70a4b09b9ea' (an offline player) from the database

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4012) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5020) ~[guava-32.1.2-jre.jar:?]
        at com.sk89q.worldguard.session.AbstractSessionManager.hasBypass(AbstractSessionManager.java:149) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.hasBypass(BukkitSessionManager.java:86) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.session.handler.EntryFlag.onCrossBoundary(EntryFlag.java:55) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:235) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.session.Session.testMoveTo(Session.java:195) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerTeleport(WorldGuardPlayerListener.java:404) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor51.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:59) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1714) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.teleportTo(ServerPlayer.java:2067) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.setCamera(ServerPlayer.java:2317) ~[?:?]
        at top.leavesmc.leaves.replay.ServerPhotographer.setFollowPlayer(ServerPhotographer.java:147) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at top.leavesmc.leaves.entity.CraftPhotographer.setFollowPlayer(CraftPhotographer.java:52) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at cn.xor7.iseeyou.EventListener.onPlayerJoin(EventListener.kt:77) ~[ISeeYou-1.2.1-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1201.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:59) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:465) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:134) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1460) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1437) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for '0e8ef417-fae9-4106-9cab-d70a4b09b9ea' (an offline player) from the database

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:153) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userHasPermission(LuckPermsVaultPermission.java:172) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.playerHas(AbstractVaultPermission.java:150) ~[?:?]
        at com.sk89q.wepif.VaultResolver.hasPermission(VaultResolver.java:100) ~[worldedit-bukkit-7.3.1.jar:?]
        at com.sk89q.wepif.PermissionsResolverManager.hasPermission(PermissionsResolverManager.java:170) ~[worldedit-bukkit-7.3.1.jar:?]
        at com.sk89q.worldguard.bukkit.WorldGuardPlugin.hasPermission(WorldGuardPlugin.java:360) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.bukkit.BukkitPlayer.hasPermission(BukkitPlayer.java:219) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.session.AbstractSessionManager.lambda$static$0(AbstractSessionManager.java:62) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.sk89q.worldguard.session.AbstractSessionManager.lambda$new$1(AbstractSessionManager.java:68) ~[worldguard-bukkit-7.0.9-dist.jar:?]
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:169) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080) ~[guava-32.1.2-jre.jar:?]
        ... 46 more
```

**Comment by MC-XiaoHei** [comment]
这似乎是因为leaves的假人隔离不完全导致的。
你使用的leaves版本是？

**Comment by YuanYuanOwO** [comment]
> 这似乎是因为leaves的假人隔离不完全导致的。 你使用的leaves版本是？

1.20.4的最后一个版本

**Comment by MC-XiaoHei** [comment]
我去ping一下leaves开发者

**Comment by MC-XiaoHei** [comment]
看起来问题是因为摄像机传送时触发事件导致的。需要leaves端进行操作

**Comment by MC-XiaoHei** [comment]
看起来问题是因为摄像机传送时触发事件导致的。需要leaves端进行操作

**Comment by MC-XiaoHei** [comment]
请尝试在新版本尝试
